name: Assign To Me Action

on:
  schedule:
    - cron: 0 0 * * *
  issue_comment:
    types: [created,edited]
  workflow_dispatch:

jobs:
  assign:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Assign the user or unassign stale assignments
        id: assign
        uses: takanome-dev/assign-issue-action@fix-rate-limit-err
        with:
          github_token: '${{ secrets.GH_SUPERUSER_TOKEN }}'
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          maintainers: takanome-dev
          enable_auto_suggestion: true
          
      # - name: On successful assignment
      #   if: steps.assign.outputs.assigned == 'yes'
      #   uses: peter-evans/create-or-update-comment@v4
      #   with:
      #     issue-number: ${{ github.event.issue.number }}
      #     body: 'User was successfully assigned, performing next steps...'
          
      # - name: On failed assignment
      #   if: steps.assign.outputs.assigned == 'no'
      #   uses: peter-evans/create-or-update-comment@v4
      #   with:
      #     issue-number: ${{ github.event.issue.number }}
      #     body: 'Assignment failed, no further action will be taken.'
